version: "2"

linters:
  enable:
    # Correctness / bugs
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - nilerr
    - nilnil
    - bodyclose
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - iface
    - loggercheck
    - errorlint
    - exptostd
    - err113
    - durationcheck
    - contextcheck
    - asasalint
    - importas

    # Security
    - gosec

    # Code quality / maintainability
    - gocritic
    - unconvert
    - unparam
    - prealloc
    - misspell
    - dupword
    - mirror
    - intrange
    - exhaustive
    - gochecknoglobals
    - fatcontext
    - forbidigo
    - errchkjson

    # Complexity
    - gocyclo
    - gocognit
    #- cyclop
    #- funlen
    #- maintidx

    # Tests
    - testifylint
    - tparallel
    - thelper
    - paralleltest
