dir: '{{.InterfaceDir}}'
filename: '{{.InterfaceName}}_mock.go'
template: testify
template-data:
  unroll-variadic: true
packages:
  baconi.co.uk/oauth/internal/app/token-introspection:
    config:
      all: true
  baconi.co.uk/oauth/internal/pkg/client:
    config:
      all: true
  baconi.co.uk/oauth/internal/pkg/grant:
    config:
      all: true
  baconi.co.uk/oauth/internal/pkg/scope:
    config:
      all: true
  baconi.co.uk/oauth/internal/pkg/token:
    config:
      all: true
  baconi.co.uk/oauth/internal/pkg/user:
    config:
      all: true
