// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockCredentialRepository creates a new instance of MockCredentialRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialRepository {
	mock := &MockCredentialRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCredentialRepository is an autogenerated mock type for the CredentialRepository type
type MockCredentialRepository struct {
	mock.Mock
}

type MockCredentialRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialRepository) EXPECT() *MockCredentialRepository_Expecter {
	return &MockCredentialRepository_Expecter{mock: &_m.Mock}
}

// FindByUsername provides a mock function for the type MockCredentialRepository
func (_mock *MockCredentialRepository) FindByUsername(username string) (Credential, error) {
	ret := _mock.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 Credential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (Credential, error)); ok {
		return returnFunc(username)
	}
	if returnFunc, ok := ret.Get(0).(func(string) Credential); ok {
		r0 = returnFunc(username)
	} else {
		r0 = ret.Get(0).(Credential)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCredentialRepository_FindByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUsername'
type MockCredentialRepository_FindByUsername_Call struct {
	*mock.Call
}

// FindByUsername is a helper method to define mock.On call
//   - username string
func (_e *MockCredentialRepository_Expecter) FindByUsername(username interface{}) *MockCredentialRepository_FindByUsername_Call {
	return &MockCredentialRepository_FindByUsername_Call{Call: _e.mock.On("FindByUsername", username)}
}

func (_c *MockCredentialRepository_FindByUsername_Call) Run(run func(username string)) *MockCredentialRepository_FindByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCredentialRepository_FindByUsername_Call) Return(credential Credential, err error) *MockCredentialRepository_FindByUsername_Call {
	_c.Call.Return(credential, err)
	return _c
}

func (_c *MockCredentialRepository_FindByUsername_Call) RunAndReturn(run func(username string) (Credential, error)) *MockCredentialRepository_FindByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockCredentialRepository
func (_mock *MockCredentialRepository) Insert(new Credential) error {
	ret := _mock.Called(new)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(Credential) error); ok {
		r0 = returnFunc(new)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCredentialRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockCredentialRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - new Credential
func (_e *MockCredentialRepository_Expecter) Insert(new interface{}) *MockCredentialRepository_Insert_Call {
	return &MockCredentialRepository_Insert_Call{Call: _e.mock.On("Insert", new)}
}

func (_c *MockCredentialRepository_Insert_Call) Run(run func(new Credential)) *MockCredentialRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Credential
		if args[0] != nil {
			arg0 = args[0].(Credential)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCredentialRepository_Insert_Call) Return(err error) *MockCredentialRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCredentialRepository_Insert_Call) RunAndReturn(run func(new Credential) error) *MockCredentialRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}
