// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthenticator creates a new instance of MockAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthenticator {
	mock := &MockAuthenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthenticator is an autogenerated mock type for the Authenticator type
type MockAuthenticator struct {
	mock.Mock
}

type MockAuthenticator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthenticator) EXPECT() *MockAuthenticator_Expecter {
	return &MockAuthenticator_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockAuthenticator
func (_mock *MockAuthenticator) Authenticate(username string, password string) (Authenticated, error) {
	ret := _mock.Called(username, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 Authenticated
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (Authenticated, error)); ok {
		return returnFunc(username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) Authenticated); ok {
		r0 = returnFunc(username, password)
	} else {
		r0 = ret.Get(0).(Authenticated)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthenticator_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockAuthenticator_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - username string
//   - password string
func (_e *MockAuthenticator_Expecter) Authenticate(username interface{}, password interface{}) *MockAuthenticator_Authenticate_Call {
	return &MockAuthenticator_Authenticate_Call{Call: _e.mock.On("Authenticate", username, password)}
}

func (_c *MockAuthenticator_Authenticate_Call) Run(run func(username string, password string)) *MockAuthenticator_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthenticator_Authenticate_Call) Return(authenticated Authenticated, err error) *MockAuthenticator_Authenticate_Call {
	_c.Call.Return(authenticated, err)
	return _c
}

func (_c *MockAuthenticator_Authenticate_Call) RunAndReturn(run func(username string, password string) (Authenticated, error)) *MockAuthenticator_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredentialRepository creates a new instance of MockCredentialRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialRepository {
	mock := &MockCredentialRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCredentialRepository is an autogenerated mock type for the CredentialRepository type
type MockCredentialRepository struct {
	mock.Mock
}

type MockCredentialRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialRepository) EXPECT() *MockCredentialRepository_Expecter {
	return &MockCredentialRepository_Expecter{mock: &_m.Mock}
}

// FindByUsername provides a mock function for the type MockCredentialRepository
func (_mock *MockCredentialRepository) FindByUsername(username string) (Credential, error) {
	ret := _mock.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 Credential
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (Credential, error)); ok {
		return returnFunc(username)
	}
	if returnFunc, ok := ret.Get(0).(func(string) Credential); ok {
		r0 = returnFunc(username)
	} else {
		r0 = ret.Get(0).(Credential)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCredentialRepository_FindByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUsername'
type MockCredentialRepository_FindByUsername_Call struct {
	*mock.Call
}

// FindByUsername is a helper method to define mock.On call
//   - username string
func (_e *MockCredentialRepository_Expecter) FindByUsername(username interface{}) *MockCredentialRepository_FindByUsername_Call {
	return &MockCredentialRepository_FindByUsername_Call{Call: _e.mock.On("FindByUsername", username)}
}

func (_c *MockCredentialRepository_FindByUsername_Call) Run(run func(username string)) *MockCredentialRepository_FindByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCredentialRepository_FindByUsername_Call) Return(credential Credential, err error) *MockCredentialRepository_FindByUsername_Call {
	_c.Call.Return(credential, err)
	return _c
}

func (_c *MockCredentialRepository_FindByUsername_Call) RunAndReturn(run func(username string) (Credential, error)) *MockCredentialRepository_FindByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockCredentialRepository
func (_mock *MockCredentialRepository) Insert(new Credential) error {
	ret := _mock.Called(new)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(Credential) error); ok {
		r0 = returnFunc(new)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCredentialRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockCredentialRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - new Credential
func (_e *MockCredentialRepository_Expecter) Insert(new interface{}) *MockCredentialRepository_Insert_Call {
	return &MockCredentialRepository_Insert_Call{Call: _e.mock.On("Insert", new)}
}

func (_c *MockCredentialRepository_Insert_Call) Run(run func(new Credential)) *MockCredentialRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Credential
		if args[0] != nil {
			arg0 = args[0].(Credential)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCredentialRepository_Insert_Call) Return(err error) *MockCredentialRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCredentialRepository_Insert_Call) RunAndReturn(run func(new Credential) error) *MockCredentialRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStatusRepository creates a new instance of MockStatusRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatusRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatusRepository {
	mock := &MockStatusRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStatusRepository is an autogenerated mock type for the StatusRepository type
type MockStatusRepository struct {
	mock.Mock
}

type MockStatusRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatusRepository) EXPECT() *MockStatusRepository_Expecter {
	return &MockStatusRepository_Expecter{mock: &_m.Mock}
}

// FindByUsername provides a mock function for the type MockStatusRepository
func (_mock *MockStatusRepository) FindByUsername(username string) (Status, error) {
	ret := _mock.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 Status
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (Status, error)); ok {
		return returnFunc(username)
	}
	if returnFunc, ok := ret.Get(0).(func(string) Status); ok {
		r0 = returnFunc(username)
	} else {
		r0 = ret.Get(0).(Status)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatusRepository_FindByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUsername'
type MockStatusRepository_FindByUsername_Call struct {
	*mock.Call
}

// FindByUsername is a helper method to define mock.On call
//   - username string
func (_e *MockStatusRepository_Expecter) FindByUsername(username interface{}) *MockStatusRepository_FindByUsername_Call {
	return &MockStatusRepository_FindByUsername_Call{Call: _e.mock.On("FindByUsername", username)}
}

func (_c *MockStatusRepository_FindByUsername_Call) Run(run func(username string)) *MockStatusRepository_FindByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStatusRepository_FindByUsername_Call) Return(status Status, err error) *MockStatusRepository_FindByUsername_Call {
	_c.Call.Return(status, err)
	return _c
}

func (_c *MockStatusRepository_FindByUsername_Call) RunAndReturn(run func(username string) (Status, error)) *MockStatusRepository_FindByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockStatusRepository
func (_mock *MockStatusRepository) Insert(status Status) error {
	ret := _mock.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(Status) error); ok {
		r0 = returnFunc(status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStatusRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockStatusRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - status Status
func (_e *MockStatusRepository_Expecter) Insert(status interface{}) *MockStatusRepository_Insert_Call {
	return &MockStatusRepository_Insert_Call{Call: _e.mock.On("Insert", status)}
}

func (_c *MockStatusRepository_Insert_Call) Run(run func(status Status)) *MockStatusRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Status
		if args[0] != nil {
			arg0 = args[0].(Status)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStatusRepository_Insert_Call) Return(err error) *MockStatusRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStatusRepository_Insert_Call) RunAndReturn(run func(status Status) error) *MockStatusRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}
