// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockStatusRepository creates a new instance of MockStatusRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatusRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatusRepository {
	mock := &MockStatusRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStatusRepository is an autogenerated mock type for the StatusRepository type
type MockStatusRepository struct {
	mock.Mock
}

type MockStatusRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatusRepository) EXPECT() *MockStatusRepository_Expecter {
	return &MockStatusRepository_Expecter{mock: &_m.Mock}
}

// FindByUsername provides a mock function for the type MockStatusRepository
func (_mock *MockStatusRepository) FindByUsername(username string) (Status, error) {
	ret := _mock.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 Status
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (Status, error)); ok {
		return returnFunc(username)
	}
	if returnFunc, ok := ret.Get(0).(func(string) Status); ok {
		r0 = returnFunc(username)
	} else {
		r0 = ret.Get(0).(Status)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatusRepository_FindByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUsername'
type MockStatusRepository_FindByUsername_Call struct {
	*mock.Call
}

// FindByUsername is a helper method to define mock.On call
//   - username string
func (_e *MockStatusRepository_Expecter) FindByUsername(username interface{}) *MockStatusRepository_FindByUsername_Call {
	return &MockStatusRepository_FindByUsername_Call{Call: _e.mock.On("FindByUsername", username)}
}

func (_c *MockStatusRepository_FindByUsername_Call) Run(run func(username string)) *MockStatusRepository_FindByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStatusRepository_FindByUsername_Call) Return(status Status, err error) *MockStatusRepository_FindByUsername_Call {
	_c.Call.Return(status, err)
	return _c
}

func (_c *MockStatusRepository_FindByUsername_Call) RunAndReturn(run func(username string) (Status, error)) *MockStatusRepository_FindByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockStatusRepository
func (_mock *MockStatusRepository) Insert(status Status) error {
	ret := _mock.Called(status)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(Status) error); ok {
		r0 = returnFunc(status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStatusRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockStatusRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - status Status
func (_e *MockStatusRepository_Expecter) Insert(status interface{}) *MockStatusRepository_Insert_Call {
	return &MockStatusRepository_Insert_Call{Call: _e.mock.On("Insert", status)}
}

func (_c *MockStatusRepository_Insert_Call) Run(run func(status Status)) *MockStatusRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Status
		if args[0] != nil {
			arg0 = args[0].(Status)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStatusRepository_Insert_Call) Return(err error) *MockStatusRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStatusRepository_Insert_Call) RunAndReturn(run func(status Status) error) *MockStatusRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}
