// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access_tokens.sql

package db

import (
	"context"
	"time"

	"baconi.co.uk/oauth/internal/pkg/client"
	"baconi.co.uk/oauth/internal/pkg/scope"
	"baconi.co.uk/oauth/internal/pkg/user"
	"github.com/google/uuid"
)

const createAccessToken = `-- name: CreateAccessToken :exec
INSERT INTO access_tokens (id, username, client_id, scopes, issued_at, expires_at, not_before)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAccessTokenParams struct {
	ID        uuid.UUID                  `db:"id"`
	Username  user.AuthenticatedUsername `db:"username"`
	ClientID  client.Id                  `db:"client_id"`
	Scopes    scope.Scopes               `db:"scopes"`
	IssuedAt  time.Time                  `db:"issued_at"`
	ExpiresAt time.Time                  `db:"expires_at"`
	NotBefore time.Time                  `db:"not_before"`
}

// CreateAccessToken
//
//	INSERT INTO access_tokens (id, username, client_id, scopes, issued_at, expires_at, not_before)
//	VALUES (?, ?, ?, ?, ?, ?, ?)
func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) error {
	_, err := q.exec(ctx, q.createAccessTokenStmt, createAccessToken,
		arg.ID,
		arg.Username,
		arg.ClientID,
		arg.Scopes,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.NotBefore,
	)
	return err
}

const deleteAccessToken = `-- name: DeleteAccessToken :exec
DELETE
FROM access_tokens
WHERE id = ?
`

// DeleteAccessToken
//
//	DELETE
//	FROM access_tokens
//	WHERE id = ?
func (q *Queries) DeleteAccessToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteAccessTokenStmt, deleteAccessToken, id)
	return err
}

const deleteExpiredAccessTokens = `-- name: DeleteExpiredAccessTokens :exec
DELETE
FROM access_tokens
WHERE datetime(expires_at) <= CURRENT_TIMESTAMP
`

// DeleteExpiredAccessTokens
//
//	DELETE
//	FROM access_tokens
//	WHERE datetime(expires_at) <= CURRENT_TIMESTAMP
func (q *Queries) DeleteExpiredAccessTokens(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteExpiredAccessTokensStmt, deleteExpiredAccessTokens)
	return err
}

const getAccessToken = `-- name: GetAccessToken :one
SELECT id, username, client_id, json(scopes), issued_at, expires_at, not_before
FROM access_tokens
WHERE id = ?
LIMIT 1
`

// GetAccessToken
//
//	SELECT id, username, client_id, json(scopes), issued_at, expires_at, not_before
//	FROM access_tokens
//	WHERE id = ?
//	LIMIT 1
func (q *Queries) GetAccessToken(ctx context.Context, id uuid.UUID) (AccessToken, error) {
	row := q.queryRow(ctx, q.getAccessTokenStmt, getAccessToken, id)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.ClientID,
		&i.Scopes,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.NotBefore,
	)
	return i, err
}
