// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client_configurations.sql

package db

import (
	"context"

	"baconi.co.uk/oauth/internal/pkg/client"
)

const getClientConfiguration = `-- name: GetClientConfiguration :one
SELECT client_id, client_type, json(redirect_uris), json(allowed_scopes), json(allowed_actions), json(allowed_grant_types)
FROM client_configurations
WHERE client_id = ?
LIMIT 1
`

// GetClientConfiguration
//
//	SELECT client_id, client_type, json(redirect_uris), json(allowed_scopes), json(allowed_actions), json(allowed_grant_types)
//	FROM client_configurations
//	WHERE client_id = ?
//	LIMIT 1
func (q *Queries) GetClientConfiguration(ctx context.Context, clientID client.Id) (ClientConfiguration, error) {
	row := q.db.QueryRowContext(ctx, getClientConfiguration, clientID)
	var i ClientConfiguration
	err := row.Scan(
		&i.ClientID,
		&i.ClientType,
		&i.RedirectUris,
		&i.AllowedScopes,
		&i.AllowedActions,
		&i.AllowedGrantTypes,
	)
	return i, err
}
