// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"baconi.co.uk/oauth/internal/pkg/client"
	"baconi.co.uk/oauth/internal/pkg/scope"
	"baconi.co.uk/oauth/internal/pkg/user"
	"github.com/google/uuid"
)

type AccessToken struct {
	ID        uuid.UUID                  `db:"id"`
	Username  user.AuthenticatedUsername `db:"username"`
	ClientID  client.Id                  `db:"client_id"`
	Scopes    scope.Scopes               `db:"scopes"`
	IssuedAt  time.Time                  `db:"issued_at"`
	ExpiresAt time.Time                  `db:"expires_at"`
	NotBefore time.Time                  `db:"not_before"`
}
