// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package client

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthenticator creates a new instance of MockAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthenticator {
	mock := &MockAuthenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthenticator is an autogenerated mock type for the Authenticator type
type MockAuthenticator struct {
	mock.Mock
}

type MockAuthenticator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthenticator) EXPECT() *MockAuthenticator_Expecter {
	return &MockAuthenticator_Expecter{mock: &_m.Mock}
}

// AuthenticateAsConfidential provides a mock function for the type MockAuthenticator
func (_mock *MockAuthenticator) AuthenticateAsConfidential(clientId string, clientSecret string) (Principal, bool) {
	ret := _mock.Called(clientId, clientSecret)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateAsConfidential")
	}

	var r0 Principal
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) (Principal, bool)); ok {
		return returnFunc(clientId, clientSecret)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) Principal); ok {
		r0 = returnFunc(clientId, clientSecret)
	} else {
		r0 = ret.Get(0).(Principal)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) bool); ok {
		r1 = returnFunc(clientId, clientSecret)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockAuthenticator_AuthenticateAsConfidential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateAsConfidential'
type MockAuthenticator_AuthenticateAsConfidential_Call struct {
	*mock.Call
}

// AuthenticateAsConfidential is a helper method to define mock.On call
//   - clientId string
//   - clientSecret string
func (_e *MockAuthenticator_Expecter) AuthenticateAsConfidential(clientId interface{}, clientSecret interface{}) *MockAuthenticator_AuthenticateAsConfidential_Call {
	return &MockAuthenticator_AuthenticateAsConfidential_Call{Call: _e.mock.On("AuthenticateAsConfidential", clientId, clientSecret)}
}

func (_c *MockAuthenticator_AuthenticateAsConfidential_Call) Run(run func(clientId string, clientSecret string)) *MockAuthenticator_AuthenticateAsConfidential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthenticator_AuthenticateAsConfidential_Call) Return(principal Principal, b bool) *MockAuthenticator_AuthenticateAsConfidential_Call {
	_c.Call.Return(principal, b)
	return _c
}

func (_c *MockAuthenticator_AuthenticateAsConfidential_Call) RunAndReturn(run func(clientId string, clientSecret string) (Principal, bool)) *MockAuthenticator_AuthenticateAsConfidential_Call {
	_c.Call.Return(run)
	return _c
}

// AuthenticateAsPublic provides a mock function for the type MockAuthenticator
func (_mock *MockAuthenticator) AuthenticateAsPublic(clientId string) (Principal, bool) {
	ret := _mock.Called(clientId)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateAsPublic")
	}

	var r0 Principal
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (Principal, bool)); ok {
		return returnFunc(clientId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) Principal); ok {
		r0 = returnFunc(clientId)
	} else {
		r0 = ret.Get(0).(Principal)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(clientId)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockAuthenticator_AuthenticateAsPublic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateAsPublic'
type MockAuthenticator_AuthenticateAsPublic_Call struct {
	*mock.Call
}

// AuthenticateAsPublic is a helper method to define mock.On call
//   - clientId string
func (_e *MockAuthenticator_Expecter) AuthenticateAsPublic(clientId interface{}) *MockAuthenticator_AuthenticateAsPublic_Call {
	return &MockAuthenticator_AuthenticateAsPublic_Call{Call: _e.mock.On("AuthenticateAsPublic", clientId)}
}

func (_c *MockAuthenticator_AuthenticateAsPublic_Call) Run(run func(clientId string)) *MockAuthenticator_AuthenticateAsPublic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthenticator_AuthenticateAsPublic_Call) Return(principal Principal, b bool) *MockAuthenticator_AuthenticateAsPublic_Call {
	_c.Call.Return(principal, b)
	return _c
}

func (_c *MockAuthenticator_AuthenticateAsPublic_Call) RunAndReturn(run func(clientId string) (Principal, bool)) *MockAuthenticator_AuthenticateAsPublic_Call {
	_c.Call.Return(run)
	return _c
}
