// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package client

import (
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthenticator creates a new instance of MockAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthenticator {
	mock := &MockAuthenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthenticator is an autogenerated mock type for the Authenticator type
type MockAuthenticator struct {
	mock.Mock
}

type MockAuthenticator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthenticator) EXPECT() *MockAuthenticator_Expecter {
	return &MockAuthenticator_Expecter{mock: &_m.Mock}
}

// AuthenticateAsConfidential provides a mock function for the type MockAuthenticator
func (_mock *MockAuthenticator) AuthenticateAsConfidential(clientId string, clientSecret string) (Principal, bool) {
	ret := _mock.Called(clientId, clientSecret)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateAsConfidential")
	}

	var r0 Principal
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) (Principal, bool)); ok {
		return returnFunc(clientId, clientSecret)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) Principal); ok {
		r0 = returnFunc(clientId, clientSecret)
	} else {
		r0 = ret.Get(0).(Principal)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) bool); ok {
		r1 = returnFunc(clientId, clientSecret)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockAuthenticator_AuthenticateAsConfidential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateAsConfidential'
type MockAuthenticator_AuthenticateAsConfidential_Call struct {
	*mock.Call
}

// AuthenticateAsConfidential is a helper method to define mock.On call
//   - clientId string
//   - clientSecret string
func (_e *MockAuthenticator_Expecter) AuthenticateAsConfidential(clientId interface{}, clientSecret interface{}) *MockAuthenticator_AuthenticateAsConfidential_Call {
	return &MockAuthenticator_AuthenticateAsConfidential_Call{Call: _e.mock.On("AuthenticateAsConfidential", clientId, clientSecret)}
}

func (_c *MockAuthenticator_AuthenticateAsConfidential_Call) Run(run func(clientId string, clientSecret string)) *MockAuthenticator_AuthenticateAsConfidential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthenticator_AuthenticateAsConfidential_Call) Return(principal Principal, b bool) *MockAuthenticator_AuthenticateAsConfidential_Call {
	_c.Call.Return(principal, b)
	return _c
}

func (_c *MockAuthenticator_AuthenticateAsConfidential_Call) RunAndReturn(run func(clientId string, clientSecret string) (Principal, bool)) *MockAuthenticator_AuthenticateAsConfidential_Call {
	_c.Call.Return(run)
	return _c
}

// AuthenticateAsPublic provides a mock function for the type MockAuthenticator
func (_mock *MockAuthenticator) AuthenticateAsPublic(clientId string) (Principal, bool) {
	ret := _mock.Called(clientId)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateAsPublic")
	}

	var r0 Principal
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (Principal, bool)); ok {
		return returnFunc(clientId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) Principal); ok {
		r0 = returnFunc(clientId)
	} else {
		r0 = ret.Get(0).(Principal)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(clientId)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockAuthenticator_AuthenticateAsPublic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateAsPublic'
type MockAuthenticator_AuthenticateAsPublic_Call struct {
	*mock.Call
}

// AuthenticateAsPublic is a helper method to define mock.On call
//   - clientId string
func (_e *MockAuthenticator_Expecter) AuthenticateAsPublic(clientId interface{}) *MockAuthenticator_AuthenticateAsPublic_Call {
	return &MockAuthenticator_AuthenticateAsPublic_Call{Call: _e.mock.On("AuthenticateAsPublic", clientId)}
}

func (_c *MockAuthenticator_AuthenticateAsPublic_Call) Run(run func(clientId string)) *MockAuthenticator_AuthenticateAsPublic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthenticator_AuthenticateAsPublic_Call) Return(principal Principal, b bool) *MockAuthenticator_AuthenticateAsPublic_Call {
	_c.Call.Return(principal, b)
	return _c
}

func (_c *MockAuthenticator_AuthenticateAsPublic_Call) RunAndReturn(run func(clientId string) (Principal, bool)) *MockAuthenticator_AuthenticateAsPublic_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPrincipalRepository creates a new instance of MockPrincipalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrincipalRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrincipalRepository {
	mock := &MockPrincipalRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPrincipalRepository is an autogenerated mock type for the PrincipalRepository type
type MockPrincipalRepository struct {
	mock.Mock
}

type MockPrincipalRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrincipalRepository) EXPECT() *MockPrincipalRepository_Expecter {
	return &MockPrincipalRepository_Expecter{mock: &_m.Mock}
}

// FindByClientId provides a mock function for the type MockPrincipalRepository
func (_mock *MockPrincipalRepository) FindByClientId(clientId string) (Principal, error) {
	ret := _mock.Called(clientId)

	if len(ret) == 0 {
		panic("no return value specified for FindByClientId")
	}

	var r0 Principal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (Principal, error)); ok {
		return returnFunc(clientId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) Principal); ok {
		r0 = returnFunc(clientId)
	} else {
		r0 = ret.Get(0).(Principal)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(clientId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPrincipalRepository_FindByClientId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByClientId'
type MockPrincipalRepository_FindByClientId_Call struct {
	*mock.Call
}

// FindByClientId is a helper method to define mock.On call
//   - clientId string
func (_e *MockPrincipalRepository_Expecter) FindByClientId(clientId interface{}) *MockPrincipalRepository_FindByClientId_Call {
	return &MockPrincipalRepository_FindByClientId_Call{Call: _e.mock.On("FindByClientId", clientId)}
}

func (_c *MockPrincipalRepository_FindByClientId_Call) Run(run func(clientId string)) *MockPrincipalRepository_FindByClientId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPrincipalRepository_FindByClientId_Call) Return(principal Principal, err error) *MockPrincipalRepository_FindByClientId_Call {
	_c.Call.Return(principal, err)
	return _c
}

func (_c *MockPrincipalRepository_FindByClientId_Call) RunAndReturn(run func(clientId string) (Principal, error)) *MockPrincipalRepository_FindByClientId_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockPrincipalRepository
func (_mock *MockPrincipalRepository) FindById(id Id) (Principal, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 Principal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(Id) (Principal, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(Id) Principal); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(Principal)
	}
	if returnFunc, ok := ret.Get(1).(func(Id) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPrincipalRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockPrincipalRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id Id
func (_e *MockPrincipalRepository_Expecter) FindById(id interface{}) *MockPrincipalRepository_FindById_Call {
	return &MockPrincipalRepository_FindById_Call{Call: _e.mock.On("FindById", id)}
}

func (_c *MockPrincipalRepository_FindById_Call) Run(run func(id Id)) *MockPrincipalRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Id
		if args[0] != nil {
			arg0 = args[0].(Id)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPrincipalRepository_FindById_Call) Return(principal Principal, err error) *MockPrincipalRepository_FindById_Call {
	_c.Call.Return(principal, err)
	return _c
}

func (_c *MockPrincipalRepository_FindById_Call) RunAndReturn(run func(id Id) (Principal, error)) *MockPrincipalRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSecretRepository creates a new instance of MockSecretRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretRepository {
	mock := &MockSecretRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSecretRepository is an autogenerated mock type for the SecretRepository type
type MockSecretRepository struct {
	mock.Mock
}

type MockSecretRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretRepository) EXPECT() *MockSecretRepository_Expecter {
	return &MockSecretRepository_Expecter{mock: &_m.Mock}
}

// FindByClient provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) FindByClient(client Id) ([]Secret, bool) {
	ret := _mock.Called(client)

	if len(ret) == 0 {
		panic("no return value specified for FindByClient")
	}

	var r0 []Secret
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(Id) ([]Secret, bool)); ok {
		return returnFunc(client)
	}
	if returnFunc, ok := ret.Get(0).(func(Id) []Secret); ok {
		r0 = returnFunc(client)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(Id) bool); ok {
		r1 = returnFunc(client)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockSecretRepository_FindByClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByClient'
type MockSecretRepository_FindByClient_Call struct {
	*mock.Call
}

// FindByClient is a helper method to define mock.On call
//   - client Id
func (_e *MockSecretRepository_Expecter) FindByClient(client interface{}) *MockSecretRepository_FindByClient_Call {
	return &MockSecretRepository_FindByClient_Call{Call: _e.mock.On("FindByClient", client)}
}

func (_c *MockSecretRepository_FindByClient_Call) Run(run func(client Id)) *MockSecretRepository_FindByClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Id
		if args[0] != nil {
			arg0 = args[0].(Id)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSecretRepository_FindByClient_Call) Return(secrets []Secret, b bool) *MockSecretRepository_FindByClient_Call {
	_c.Call.Return(secrets, b)
	return _c
}

func (_c *MockSecretRepository_FindByClient_Call) RunAndReturn(run func(client Id) ([]Secret, bool)) *MockSecretRepository_FindByClient_Call {
	_c.Call.Return(run)
	return _c
}

// FindByClientId provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) FindByClientId(clientId string) ([]Secret, bool) {
	ret := _mock.Called(clientId)

	if len(ret) == 0 {
		panic("no return value specified for FindByClientId")
	}

	var r0 []Secret
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) ([]Secret, bool)); ok {
		return returnFunc(clientId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []Secret); ok {
		r0 = returnFunc(clientId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(clientId)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockSecretRepository_FindByClientId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByClientId'
type MockSecretRepository_FindByClientId_Call struct {
	*mock.Call
}

// FindByClientId is a helper method to define mock.On call
//   - clientId string
func (_e *MockSecretRepository_Expecter) FindByClientId(clientId interface{}) *MockSecretRepository_FindByClientId_Call {
	return &MockSecretRepository_FindByClientId_Call{Call: _e.mock.On("FindByClientId", clientId)}
}

func (_c *MockSecretRepository_FindByClientId_Call) Run(run func(clientId string)) *MockSecretRepository_FindByClientId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSecretRepository_FindByClientId_Call) Return(secrets []Secret, b bool) *MockSecretRepository_FindByClientId_Call {
	_c.Call.Return(secrets, b)
	return _c
}

func (_c *MockSecretRepository_FindByClientId_Call) RunAndReturn(run func(clientId string) ([]Secret, bool)) *MockSecretRepository_FindByClientId_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) FindById(id uuid.UUID) (Secret, bool) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 Secret
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (Secret, bool)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) Secret); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(Secret)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) bool); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockSecretRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockSecretRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockSecretRepository_Expecter) FindById(id interface{}) *MockSecretRepository_FindById_Call {
	return &MockSecretRepository_FindById_Call{Call: _e.mock.On("FindById", id)}
}

func (_c *MockSecretRepository_FindById_Call) Run(run func(id uuid.UUID)) *MockSecretRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSecretRepository_FindById_Call) Return(secret Secret, b bool) *MockSecretRepository_FindById_Call {
	_c.Call.Return(secret, b)
	return _c
}

func (_c *MockSecretRepository_FindById_Call) RunAndReturn(run func(id uuid.UUID) (Secret, bool)) *MockSecretRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}
