// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package client

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPrincipalRepository creates a new instance of MockPrincipalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrincipalRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrincipalRepository {
	mock := &MockPrincipalRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPrincipalRepository is an autogenerated mock type for the PrincipalRepository type
type MockPrincipalRepository struct {
	mock.Mock
}

type MockPrincipalRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrincipalRepository) EXPECT() *MockPrincipalRepository_Expecter {
	return &MockPrincipalRepository_Expecter{mock: &_m.Mock}
}

// FindByClientId provides a mock function for the type MockPrincipalRepository
func (_mock *MockPrincipalRepository) FindByClientId(clientId string) (Principal, bool) {
	ret := _mock.Called(clientId)

	if len(ret) == 0 {
		panic("no return value specified for FindByClientId")
	}

	var r0 Principal
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (Principal, bool)); ok {
		return returnFunc(clientId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) Principal); ok {
		r0 = returnFunc(clientId)
	} else {
		r0 = ret.Get(0).(Principal)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(clientId)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockPrincipalRepository_FindByClientId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByClientId'
type MockPrincipalRepository_FindByClientId_Call struct {
	*mock.Call
}

// FindByClientId is a helper method to define mock.On call
//   - clientId string
func (_e *MockPrincipalRepository_Expecter) FindByClientId(clientId interface{}) *MockPrincipalRepository_FindByClientId_Call {
	return &MockPrincipalRepository_FindByClientId_Call{Call: _e.mock.On("FindByClientId", clientId)}
}

func (_c *MockPrincipalRepository_FindByClientId_Call) Run(run func(clientId string)) *MockPrincipalRepository_FindByClientId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPrincipalRepository_FindByClientId_Call) Return(principal Principal, b bool) *MockPrincipalRepository_FindByClientId_Call {
	_c.Call.Return(principal, b)
	return _c
}

func (_c *MockPrincipalRepository_FindByClientId_Call) RunAndReturn(run func(clientId string) (Principal, bool)) *MockPrincipalRepository_FindByClientId_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockPrincipalRepository
func (_mock *MockPrincipalRepository) FindById(id Id) (Principal, bool) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 Principal
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(Id) (Principal, bool)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(Id) Principal); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(Principal)
	}
	if returnFunc, ok := ret.Get(1).(func(Id) bool); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockPrincipalRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockPrincipalRepository_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id Id
func (_e *MockPrincipalRepository_Expecter) FindById(id interface{}) *MockPrincipalRepository_FindById_Call {
	return &MockPrincipalRepository_FindById_Call{Call: _e.mock.On("FindById", id)}
}

func (_c *MockPrincipalRepository_FindById_Call) Run(run func(id Id)) *MockPrincipalRepository_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Id
		if args[0] != nil {
			arg0 = args[0].(Id)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPrincipalRepository_FindById_Call) Return(principal Principal, b bool) *MockPrincipalRepository_FindById_Call {
	_c.Call.Return(principal, b)
	return _c
}

func (_c *MockPrincipalRepository_FindById_Call) RunAndReturn(run func(id Id) (Principal, bool)) *MockPrincipalRepository_FindById_Call {
	_c.Call.Return(run)
	return _c
}
