// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package token_introspection

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIntrospector creates a new instance of MockIntrospector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIntrospector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIntrospector {
	mock := &MockIntrospector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIntrospector is an autogenerated mock type for the Introspector type
type MockIntrospector struct {
	mock.Mock
}

type MockIntrospector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIntrospector) EXPECT() *MockIntrospector_Expecter {
	return &MockIntrospector_Expecter{mock: &_m.Mock}
}

// introspect provides a mock function for the type MockIntrospector
func (_mock *MockIntrospector) introspect(requestMoqParam request) (response, error) {
	ret := _mock.Called(requestMoqParam)

	if len(ret) == 0 {
		panic("no return value specified for introspect")
	}

	var r0 response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(request) (response, error)); ok {
		return returnFunc(requestMoqParam)
	}
	if returnFunc, ok := ret.Get(0).(func(request) response); ok {
		r0 = returnFunc(requestMoqParam)
	} else {
		r0 = ret.Get(0).(response)
	}
	if returnFunc, ok := ret.Get(1).(func(request) error); ok {
		r1 = returnFunc(requestMoqParam)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIntrospector_introspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'introspect'
type MockIntrospector_introspect_Call struct {
	*mock.Call
}

// introspect is a helper method to define mock.On call
//   - requestMoqParam request
func (_e *MockIntrospector_Expecter) introspect(requestMoqParam interface{}) *MockIntrospector_introspect_Call {
	return &MockIntrospector_introspect_Call{Call: _e.mock.On("introspect", requestMoqParam)}
}

func (_c *MockIntrospector_introspect_Call) Run(run func(requestMoqParam request)) *MockIntrospector_introspect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 request
		if args[0] != nil {
			arg0 = args[0].(request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIntrospector_introspect_Call) Return(responseMoqParam response, err error) *MockIntrospector_introspect_Call {
	_c.Call.Return(responseMoqParam, err)
	return _c
}

func (_c *MockIntrospector_introspect_Call) RunAndReturn(run func(requestMoqParam request) (response, error)) *MockIntrospector_introspect_Call {
	_c.Call.Return(run)
	return _c
}
