// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package token

import (
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthenticator creates a new instance of MockAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthenticator[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthenticator[T] {
	mock := &MockAuthenticator[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthenticator is an autogenerated mock type for the Authenticator type
type MockAuthenticator[T any] struct {
	mock.Mock
}

type MockAuthenticator_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockAuthenticator[T]) EXPECT() *MockAuthenticator_Expecter[T] {
	return &MockAuthenticator_Expecter[T]{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockAuthenticator
func (_mock *MockAuthenticator[T]) Authenticate(token uuid.UUID) (T, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (T, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) T); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthenticator_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockAuthenticator_Authenticate_Call[T any] struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - token uuid.UUID
func (_e *MockAuthenticator_Expecter[T]) Authenticate(token interface{}) *MockAuthenticator_Authenticate_Call[T] {
	return &MockAuthenticator_Authenticate_Call[T]{Call: _e.mock.On("Authenticate", token)}
}

func (_c *MockAuthenticator_Authenticate_Call[T]) Run(run func(token uuid.UUID)) *MockAuthenticator_Authenticate_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthenticator_Authenticate_Call[T]) Return(v T, err error) *MockAuthenticator_Authenticate_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockAuthenticator_Authenticate_Call[T]) RunAndReturn(run func(token uuid.UUID) (T, error)) *MockAuthenticator_Authenticate_Call[T] {
	_c.Call.Return(run)
	return _c
}
