// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package token

import (
	"baconi.co.uk/oauth/internal/pkg/client"
	"baconi.co.uk/oauth/internal/pkg/scope"
	"baconi.co.uk/oauth/internal/pkg/user"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIssuer creates a new instance of MockIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIssuer[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIssuer[T] {
	mock := &MockIssuer[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIssuer is an autogenerated mock type for the Issuer type
type MockIssuer[T any] struct {
	mock.Mock
}

type MockIssuer_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockIssuer[T]) EXPECT() *MockIssuer_Expecter[T] {
	return &MockIssuer_Expecter[T]{mock: &_m.Mock}
}

// Issue provides a mock function for the type MockIssuer
func (_mock *MockIssuer[T]) Issue(username user.AuthenticatedUsername, clientId client.Id, scopes scope.Scopes) (T, error) {
	ret := _mock.Called(username, clientId, scopes)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(user.AuthenticatedUsername, client.Id, scope.Scopes) (T, error)); ok {
		return returnFunc(username, clientId, scopes)
	}
	if returnFunc, ok := ret.Get(0).(func(user.AuthenticatedUsername, client.Id, scope.Scopes) T); ok {
		r0 = returnFunc(username, clientId, scopes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(user.AuthenticatedUsername, client.Id, scope.Scopes) error); ok {
		r1 = returnFunc(username, clientId, scopes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIssuer_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type MockIssuer_Issue_Call[T any] struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - username user.AuthenticatedUsername
//   - clientId client.Id
//   - scopes scope.Scopes
func (_e *MockIssuer_Expecter[T]) Issue(username interface{}, clientId interface{}, scopes interface{}) *MockIssuer_Issue_Call[T] {
	return &MockIssuer_Issue_Call[T]{Call: _e.mock.On("Issue", username, clientId, scopes)}
}

func (_c *MockIssuer_Issue_Call[T]) Run(run func(username user.AuthenticatedUsername, clientId client.Id, scopes scope.Scopes)) *MockIssuer_Issue_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 user.AuthenticatedUsername
		if args[0] != nil {
			arg0 = args[0].(user.AuthenticatedUsername)
		}
		var arg1 client.Id
		if args[1] != nil {
			arg1 = args[1].(client.Id)
		}
		var arg2 scope.Scopes
		if args[2] != nil {
			arg2 = args[2].(scope.Scopes)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIssuer_Issue_Call[T]) Return(v T, err error) *MockIssuer_Issue_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockIssuer_Issue_Call[T]) RunAndReturn(run func(username user.AuthenticatedUsername, clientId client.Id, scopes scope.Scopes) (T, error)) *MockIssuer_Issue_Call[T] {
	_c.Call.Return(run)
	return _c
}
