// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package token

import (
	"baconi.co.uk/oauth/internal/pkg/client"
	"baconi.co.uk/oauth/internal/pkg/scope"
	"baconi.co.uk/oauth/internal/pkg/user"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthenticator creates a new instance of MockAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthenticator[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthenticator[T] {
	mock := &MockAuthenticator[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthenticator is an autogenerated mock type for the Authenticator type
type MockAuthenticator[T any] struct {
	mock.Mock
}

type MockAuthenticator_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockAuthenticator[T]) EXPECT() *MockAuthenticator_Expecter[T] {
	return &MockAuthenticator_Expecter[T]{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockAuthenticator
func (_mock *MockAuthenticator[T]) Authenticate(token uuid.UUID) (T, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (T, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) T); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthenticator_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockAuthenticator_Authenticate_Call[T any] struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - token uuid.UUID
func (_e *MockAuthenticator_Expecter[T]) Authenticate(token interface{}) *MockAuthenticator_Authenticate_Call[T] {
	return &MockAuthenticator_Authenticate_Call[T]{Call: _e.mock.On("Authenticate", token)}
}

func (_c *MockAuthenticator_Authenticate_Call[T]) Run(run func(token uuid.UUID)) *MockAuthenticator_Authenticate_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthenticator_Authenticate_Call[T]) Return(v T, err error) *MockAuthenticator_Authenticate_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockAuthenticator_Authenticate_Call[T]) RunAndReturn(run func(token uuid.UUID) (T, error)) *MockAuthenticator_Authenticate_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockIssuer creates a new instance of MockIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIssuer[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIssuer[T] {
	mock := &MockIssuer[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIssuer is an autogenerated mock type for the Issuer type
type MockIssuer[T any] struct {
	mock.Mock
}

type MockIssuer_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockIssuer[T]) EXPECT() *MockIssuer_Expecter[T] {
	return &MockIssuer_Expecter[T]{mock: &_m.Mock}
}

// Issue provides a mock function for the type MockIssuer
func (_mock *MockIssuer[T]) Issue(username user.AuthenticatedUsername, clientId client.Id, scopes scope.Scopes) (T, error) {
	ret := _mock.Called(username, clientId, scopes)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(user.AuthenticatedUsername, client.Id, scope.Scopes) (T, error)); ok {
		return returnFunc(username, clientId, scopes)
	}
	if returnFunc, ok := ret.Get(0).(func(user.AuthenticatedUsername, client.Id, scope.Scopes) T); ok {
		r0 = returnFunc(username, clientId, scopes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(user.AuthenticatedUsername, client.Id, scope.Scopes) error); ok {
		r1 = returnFunc(username, clientId, scopes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIssuer_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type MockIssuer_Issue_Call[T any] struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - username user.AuthenticatedUsername
//   - clientId client.Id
//   - scopes scope.Scopes
func (_e *MockIssuer_Expecter[T]) Issue(username interface{}, clientId interface{}, scopes interface{}) *MockIssuer_Issue_Call[T] {
	return &MockIssuer_Issue_Call[T]{Call: _e.mock.On("Issue", username, clientId, scopes)}
}

func (_c *MockIssuer_Issue_Call[T]) Run(run func(username user.AuthenticatedUsername, clientId client.Id, scopes scope.Scopes)) *MockIssuer_Issue_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 user.AuthenticatedUsername
		if args[0] != nil {
			arg0 = args[0].(user.AuthenticatedUsername)
		}
		var arg1 client.Id
		if args[1] != nil {
			arg1 = args[1].(client.Id)
		}
		var arg2 scope.Scopes
		if args[2] != nil {
			arg2 = args[2].(scope.Scopes)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIssuer_Issue_Call[T]) Return(v T, err error) *MockIssuer_Issue_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockIssuer_Issue_Call[T]) RunAndReturn(run func(username user.AuthenticatedUsername, clientId client.Id, scopes scope.Scopes) (T, error)) *MockIssuer_Issue_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryCreate creates a new instance of MockRepositoryCreate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryCreate[R any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryCreate[R] {
	mock := &MockRepositoryCreate[R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryCreate is an autogenerated mock type for the RepositoryCreate type
type MockRepositoryCreate[R any] struct {
	mock.Mock
}

type MockRepositoryCreate_Expecter[R any] struct {
	mock *mock.Mock
}

func (_m *MockRepositoryCreate[R]) EXPECT() *MockRepositoryCreate_Expecter[R] {
	return &MockRepositoryCreate_Expecter[R]{mock: &_m.Mock}
}

// Insert provides a mock function for the type MockRepositoryCreate
func (_mock *MockRepositoryCreate[R]) Insert(new R) error {
	ret := _mock.Called(new)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(R) error); ok {
		r0 = returnFunc(new)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryCreate_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockRepositoryCreate_Insert_Call[R any] struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - new R
func (_e *MockRepositoryCreate_Expecter[R]) Insert(new interface{}) *MockRepositoryCreate_Insert_Call[R] {
	return &MockRepositoryCreate_Insert_Call[R]{Call: _e.mock.On("Insert", new)}
}

func (_c *MockRepositoryCreate_Insert_Call[R]) Run(run func(new R)) *MockRepositoryCreate_Insert_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 R
		if args[0] != nil {
			arg0 = args[0].(R)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryCreate_Insert_Call[R]) Return(err error) *MockRepositoryCreate_Insert_Call[R] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryCreate_Insert_Call[R]) RunAndReturn(run func(new R) error) *MockRepositoryCreate_Insert_Call[R] {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryRead creates a new instance of MockRepositoryRead. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryRead[R any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryRead[R] {
	mock := &MockRepositoryRead[R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryRead is an autogenerated mock type for the RepositoryRead type
type MockRepositoryRead[R any] struct {
	mock.Mock
}

type MockRepositoryRead_Expecter[R any] struct {
	mock *mock.Mock
}

func (_m *MockRepositoryRead[R]) EXPECT() *MockRepositoryRead_Expecter[R] {
	return &MockRepositoryRead_Expecter[R]{mock: &_m.Mock}
}

// FindById provides a mock function for the type MockRepositoryRead
func (_mock *MockRepositoryRead[R]) FindById(id uuid.UUID) (R, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 R
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (R, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) R); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(R)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryRead_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockRepositoryRead_FindById_Call[R any] struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockRepositoryRead_Expecter[R]) FindById(id interface{}) *MockRepositoryRead_FindById_Call[R] {
	return &MockRepositoryRead_FindById_Call[R]{Call: _e.mock.On("FindById", id)}
}

func (_c *MockRepositoryRead_FindById_Call[R]) Run(run func(id uuid.UUID)) *MockRepositoryRead_FindById_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryRead_FindById_Call[R]) Return(v R, err error) *MockRepositoryRead_FindById_Call[R] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockRepositoryRead_FindById_Call[R]) RunAndReturn(run func(id uuid.UUID) (R, error)) *MockRepositoryRead_FindById_Call[R] {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryDelete creates a new instance of MockRepositoryDelete. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryDelete[R any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryDelete[R] {
	mock := &MockRepositoryDelete[R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryDelete is an autogenerated mock type for the RepositoryDelete type
type MockRepositoryDelete[R any] struct {
	mock.Mock
}

type MockRepositoryDelete_Expecter[R any] struct {
	mock *mock.Mock
}

func (_m *MockRepositoryDelete[R]) EXPECT() *MockRepositoryDelete_Expecter[R] {
	return &MockRepositoryDelete_Expecter[R]{mock: &_m.Mock}
}

// DeleteById provides a mock function for the type MockRepositoryDelete
func (_mock *MockRepositoryDelete[R]) DeleteById(id uuid.UUID) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryDelete_DeleteById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteById'
type MockRepositoryDelete_DeleteById_Call[R any] struct {
	*mock.Call
}

// DeleteById is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockRepositoryDelete_Expecter[R]) DeleteById(id interface{}) *MockRepositoryDelete_DeleteById_Call[R] {
	return &MockRepositoryDelete_DeleteById_Call[R]{Call: _e.mock.On("DeleteById", id)}
}

func (_c *MockRepositoryDelete_DeleteById_Call[R]) Run(run func(id uuid.UUID)) *MockRepositoryDelete_DeleteById_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryDelete_DeleteById_Call[R]) Return(err error) *MockRepositoryDelete_DeleteById_Call[R] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryDelete_DeleteById_Call[R]) RunAndReturn(run func(id uuid.UUID) error) *MockRepositoryDelete_DeleteById_Call[R] {
	_c.Call.Return(run)
	return _c
}

// DeleteByRecord provides a mock function for the type MockRepositoryDelete
func (_mock *MockRepositoryDelete[R]) DeleteByRecord(record R) error {
	ret := _mock.Called(record)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByRecord")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(R) error); ok {
		r0 = returnFunc(record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryDelete_DeleteByRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByRecord'
type MockRepositoryDelete_DeleteByRecord_Call[R any] struct {
	*mock.Call
}

// DeleteByRecord is a helper method to define mock.On call
//   - record R
func (_e *MockRepositoryDelete_Expecter[R]) DeleteByRecord(record interface{}) *MockRepositoryDelete_DeleteByRecord_Call[R] {
	return &MockRepositoryDelete_DeleteByRecord_Call[R]{Call: _e.mock.On("DeleteByRecord", record)}
}

func (_c *MockRepositoryDelete_DeleteByRecord_Call[R]) Run(run func(record R)) *MockRepositoryDelete_DeleteByRecord_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 R
		if args[0] != nil {
			arg0 = args[0].(R)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryDelete_DeleteByRecord_Call[R]) Return(err error) *MockRepositoryDelete_DeleteByRecord_Call[R] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryDelete_DeleteByRecord_Call[R]) RunAndReturn(run func(record R) error) *MockRepositoryDelete_DeleteByRecord_Call[R] {
	_c.Call.Return(run)
	return _c
}

// DeletedExpired provides a mock function for the type MockRepositoryDelete
func (_mock *MockRepositoryDelete[R]) DeletedExpired() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeletedExpired")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryDelete_DeletedExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletedExpired'
type MockRepositoryDelete_DeletedExpired_Call[R any] struct {
	*mock.Call
}

// DeletedExpired is a helper method to define mock.On call
func (_e *MockRepositoryDelete_Expecter[R]) DeletedExpired() *MockRepositoryDelete_DeletedExpired_Call[R] {
	return &MockRepositoryDelete_DeletedExpired_Call[R]{Call: _e.mock.On("DeletedExpired")}
}

func (_c *MockRepositoryDelete_DeletedExpired_Call[R]) Run(run func()) *MockRepositoryDelete_DeletedExpired_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryDelete_DeletedExpired_Call[R]) Return(err error) *MockRepositoryDelete_DeletedExpired_Call[R] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryDelete_DeletedExpired_Call[R]) RunAndReturn(run func() error) *MockRepositoryDelete_DeletedExpired_Call[R] {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryReadDelete creates a new instance of MockRepositoryReadDelete. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryReadDelete[R any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryReadDelete[R] {
	mock := &MockRepositoryReadDelete[R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryReadDelete is an autogenerated mock type for the RepositoryReadDelete type
type MockRepositoryReadDelete[R any] struct {
	mock.Mock
}

type MockRepositoryReadDelete_Expecter[R any] struct {
	mock *mock.Mock
}

func (_m *MockRepositoryReadDelete[R]) EXPECT() *MockRepositoryReadDelete_Expecter[R] {
	return &MockRepositoryReadDelete_Expecter[R]{mock: &_m.Mock}
}

// DeleteById provides a mock function for the type MockRepositoryReadDelete
func (_mock *MockRepositoryReadDelete[R]) DeleteById(id uuid.UUID) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryReadDelete_DeleteById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteById'
type MockRepositoryReadDelete_DeleteById_Call[R any] struct {
	*mock.Call
}

// DeleteById is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockRepositoryReadDelete_Expecter[R]) DeleteById(id interface{}) *MockRepositoryReadDelete_DeleteById_Call[R] {
	return &MockRepositoryReadDelete_DeleteById_Call[R]{Call: _e.mock.On("DeleteById", id)}
}

func (_c *MockRepositoryReadDelete_DeleteById_Call[R]) Run(run func(id uuid.UUID)) *MockRepositoryReadDelete_DeleteById_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryReadDelete_DeleteById_Call[R]) Return(err error) *MockRepositoryReadDelete_DeleteById_Call[R] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryReadDelete_DeleteById_Call[R]) RunAndReturn(run func(id uuid.UUID) error) *MockRepositoryReadDelete_DeleteById_Call[R] {
	_c.Call.Return(run)
	return _c
}

// DeleteByRecord provides a mock function for the type MockRepositoryReadDelete
func (_mock *MockRepositoryReadDelete[R]) DeleteByRecord(record R) error {
	ret := _mock.Called(record)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByRecord")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(R) error); ok {
		r0 = returnFunc(record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryReadDelete_DeleteByRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByRecord'
type MockRepositoryReadDelete_DeleteByRecord_Call[R any] struct {
	*mock.Call
}

// DeleteByRecord is a helper method to define mock.On call
//   - record R
func (_e *MockRepositoryReadDelete_Expecter[R]) DeleteByRecord(record interface{}) *MockRepositoryReadDelete_DeleteByRecord_Call[R] {
	return &MockRepositoryReadDelete_DeleteByRecord_Call[R]{Call: _e.mock.On("DeleteByRecord", record)}
}

func (_c *MockRepositoryReadDelete_DeleteByRecord_Call[R]) Run(run func(record R)) *MockRepositoryReadDelete_DeleteByRecord_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 R
		if args[0] != nil {
			arg0 = args[0].(R)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryReadDelete_DeleteByRecord_Call[R]) Return(err error) *MockRepositoryReadDelete_DeleteByRecord_Call[R] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryReadDelete_DeleteByRecord_Call[R]) RunAndReturn(run func(record R) error) *MockRepositoryReadDelete_DeleteByRecord_Call[R] {
	_c.Call.Return(run)
	return _c
}

// DeletedExpired provides a mock function for the type MockRepositoryReadDelete
func (_mock *MockRepositoryReadDelete[R]) DeletedExpired() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeletedExpired")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryReadDelete_DeletedExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletedExpired'
type MockRepositoryReadDelete_DeletedExpired_Call[R any] struct {
	*mock.Call
}

// DeletedExpired is a helper method to define mock.On call
func (_e *MockRepositoryReadDelete_Expecter[R]) DeletedExpired() *MockRepositoryReadDelete_DeletedExpired_Call[R] {
	return &MockRepositoryReadDelete_DeletedExpired_Call[R]{Call: _e.mock.On("DeletedExpired")}
}

func (_c *MockRepositoryReadDelete_DeletedExpired_Call[R]) Run(run func()) *MockRepositoryReadDelete_DeletedExpired_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryReadDelete_DeletedExpired_Call[R]) Return(err error) *MockRepositoryReadDelete_DeletedExpired_Call[R] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryReadDelete_DeletedExpired_Call[R]) RunAndReturn(run func() error) *MockRepositoryReadDelete_DeletedExpired_Call[R] {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockRepositoryReadDelete
func (_mock *MockRepositoryReadDelete[R]) FindById(id uuid.UUID) (R, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 R
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (R, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) R); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(R)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryReadDelete_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockRepositoryReadDelete_FindById_Call[R any] struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockRepositoryReadDelete_Expecter[R]) FindById(id interface{}) *MockRepositoryReadDelete_FindById_Call[R] {
	return &MockRepositoryReadDelete_FindById_Call[R]{Call: _e.mock.On("FindById", id)}
}

func (_c *MockRepositoryReadDelete_FindById_Call[R]) Run(run func(id uuid.UUID)) *MockRepositoryReadDelete_FindById_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryReadDelete_FindById_Call[R]) Return(v R, err error) *MockRepositoryReadDelete_FindById_Call[R] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockRepositoryReadDelete_FindById_Call[R]) RunAndReturn(run func(id uuid.UUID) (R, error)) *MockRepositoryReadDelete_FindById_Call[R] {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository[R any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository[R] {
	mock := &MockRepository[R]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository[R any] struct {
	mock.Mock
}

type MockRepository_Expecter[R any] struct {
	mock *mock.Mock
}

func (_m *MockRepository[R]) EXPECT() *MockRepository_Expecter[R] {
	return &MockRepository_Expecter[R]{mock: &_m.Mock}
}

// DeleteById provides a mock function for the type MockRepository
func (_mock *MockRepository[R]) DeleteById(id uuid.UUID) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteById'
type MockRepository_DeleteById_Call[R any] struct {
	*mock.Call
}

// DeleteById is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockRepository_Expecter[R]) DeleteById(id interface{}) *MockRepository_DeleteById_Call[R] {
	return &MockRepository_DeleteById_Call[R]{Call: _e.mock.On("DeleteById", id)}
}

func (_c *MockRepository_DeleteById_Call[R]) Run(run func(id uuid.UUID)) *MockRepository_DeleteById_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteById_Call[R]) Return(err error) *MockRepository_DeleteById_Call[R] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteById_Call[R]) RunAndReturn(run func(id uuid.UUID) error) *MockRepository_DeleteById_Call[R] {
	_c.Call.Return(run)
	return _c
}

// DeleteByRecord provides a mock function for the type MockRepository
func (_mock *MockRepository[R]) DeleteByRecord(record R) error {
	ret := _mock.Called(record)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByRecord")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(R) error); ok {
		r0 = returnFunc(record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteByRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByRecord'
type MockRepository_DeleteByRecord_Call[R any] struct {
	*mock.Call
}

// DeleteByRecord is a helper method to define mock.On call
//   - record R
func (_e *MockRepository_Expecter[R]) DeleteByRecord(record interface{}) *MockRepository_DeleteByRecord_Call[R] {
	return &MockRepository_DeleteByRecord_Call[R]{Call: _e.mock.On("DeleteByRecord", record)}
}

func (_c *MockRepository_DeleteByRecord_Call[R]) Run(run func(record R)) *MockRepository_DeleteByRecord_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 R
		if args[0] != nil {
			arg0 = args[0].(R)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteByRecord_Call[R]) Return(err error) *MockRepository_DeleteByRecord_Call[R] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteByRecord_Call[R]) RunAndReturn(run func(record R) error) *MockRepository_DeleteByRecord_Call[R] {
	_c.Call.Return(run)
	return _c
}

// DeletedExpired provides a mock function for the type MockRepository
func (_mock *MockRepository[R]) DeletedExpired() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeletedExpired")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeletedExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletedExpired'
type MockRepository_DeletedExpired_Call[R any] struct {
	*mock.Call
}

// DeletedExpired is a helper method to define mock.On call
func (_e *MockRepository_Expecter[R]) DeletedExpired() *MockRepository_DeletedExpired_Call[R] {
	return &MockRepository_DeletedExpired_Call[R]{Call: _e.mock.On("DeletedExpired")}
}

func (_c *MockRepository_DeletedExpired_Call[R]) Run(run func()) *MockRepository_DeletedExpired_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_DeletedExpired_Call[R]) Return(err error) *MockRepository_DeletedExpired_Call[R] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeletedExpired_Call[R]) RunAndReturn(run func() error) *MockRepository_DeletedExpired_Call[R] {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockRepository
func (_mock *MockRepository[R]) FindById(id uuid.UUID) (R, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 R
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (R, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) R); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(R)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockRepository_FindById_Call[R any] struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockRepository_Expecter[R]) FindById(id interface{}) *MockRepository_FindById_Call[R] {
	return &MockRepository_FindById_Call[R]{Call: _e.mock.On("FindById", id)}
}

func (_c *MockRepository_FindById_Call[R]) Run(run func(id uuid.UUID)) *MockRepository_FindById_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_FindById_Call[R]) Return(v R, err error) *MockRepository_FindById_Call[R] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockRepository_FindById_Call[R]) RunAndReturn(run func(id uuid.UUID) (R, error)) *MockRepository_FindById_Call[R] {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockRepository
func (_mock *MockRepository[R]) Insert(new R) error {
	ret := _mock.Called(new)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(R) error); ok {
		r0 = returnFunc(new)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockRepository_Insert_Call[R any] struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - new R
func (_e *MockRepository_Expecter[R]) Insert(new interface{}) *MockRepository_Insert_Call[R] {
	return &MockRepository_Insert_Call[R]{Call: _e.mock.On("Insert", new)}
}

func (_c *MockRepository_Insert_Call[R]) Run(run func(new R)) *MockRepository_Insert_Call[R] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 R
		if args[0] != nil {
			arg0 = args[0].(R)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Insert_Call[R]) Return(err error) *MockRepository_Insert_Call[R] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Insert_Call[R]) RunAndReturn(run func(new R) error) *MockRepository_Insert_Call[R] {
	_c.Call.Return(run)
	return _c
}
