// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package token

import (
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepositoryWithMigrations creates a new instance of MockRepositoryWithMigrations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryWithMigrations[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryWithMigrations[T] {
	mock := &MockRepositoryWithMigrations[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepositoryWithMigrations is an autogenerated mock type for the RepositoryWithMigrations type
type MockRepositoryWithMigrations[T any] struct {
	mock.Mock
}

type MockRepositoryWithMigrations_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockRepositoryWithMigrations[T]) EXPECT() *MockRepositoryWithMigrations_Expecter[T] {
	return &MockRepositoryWithMigrations_Expecter[T]{mock: &_m.Mock}
}

// DeleteById provides a mock function for the type MockRepositoryWithMigrations
func (_mock *MockRepositoryWithMigrations[T]) DeleteById(id uuid.UUID) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryWithMigrations_DeleteById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteById'
type MockRepositoryWithMigrations_DeleteById_Call[T any] struct {
	*mock.Call
}

// DeleteById is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockRepositoryWithMigrations_Expecter[T]) DeleteById(id interface{}) *MockRepositoryWithMigrations_DeleteById_Call[T] {
	return &MockRepositoryWithMigrations_DeleteById_Call[T]{Call: _e.mock.On("DeleteById", id)}
}

func (_c *MockRepositoryWithMigrations_DeleteById_Call[T]) Run(run func(id uuid.UUID)) *MockRepositoryWithMigrations_DeleteById_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryWithMigrations_DeleteById_Call[T]) Return(err error) *MockRepositoryWithMigrations_DeleteById_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryWithMigrations_DeleteById_Call[T]) RunAndReturn(run func(id uuid.UUID) error) *MockRepositoryWithMigrations_DeleteById_Call[T] {
	_c.Call.Return(run)
	return _c
}

// DeleteByRecord provides a mock function for the type MockRepositoryWithMigrations
func (_mock *MockRepositoryWithMigrations[T]) DeleteByRecord(record T) error {
	ret := _mock.Called(record)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByRecord")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(T) error); ok {
		r0 = returnFunc(record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryWithMigrations_DeleteByRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByRecord'
type MockRepositoryWithMigrations_DeleteByRecord_Call[T any] struct {
	*mock.Call
}

// DeleteByRecord is a helper method to define mock.On call
//   - record T
func (_e *MockRepositoryWithMigrations_Expecter[T]) DeleteByRecord(record interface{}) *MockRepositoryWithMigrations_DeleteByRecord_Call[T] {
	return &MockRepositoryWithMigrations_DeleteByRecord_Call[T]{Call: _e.mock.On("DeleteByRecord", record)}
}

func (_c *MockRepositoryWithMigrations_DeleteByRecord_Call[T]) Run(run func(record T)) *MockRepositoryWithMigrations_DeleteByRecord_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 T
		if args[0] != nil {
			arg0 = args[0].(T)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryWithMigrations_DeleteByRecord_Call[T]) Return(err error) *MockRepositoryWithMigrations_DeleteByRecord_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryWithMigrations_DeleteByRecord_Call[T]) RunAndReturn(run func(record T) error) *MockRepositoryWithMigrations_DeleteByRecord_Call[T] {
	_c.Call.Return(run)
	return _c
}

// DeletedExpired provides a mock function for the type MockRepositoryWithMigrations
func (_mock *MockRepositoryWithMigrations[T]) DeletedExpired() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeletedExpired")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryWithMigrations_DeletedExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletedExpired'
type MockRepositoryWithMigrations_DeletedExpired_Call[T any] struct {
	*mock.Call
}

// DeletedExpired is a helper method to define mock.On call
func (_e *MockRepositoryWithMigrations_Expecter[T]) DeletedExpired() *MockRepositoryWithMigrations_DeletedExpired_Call[T] {
	return &MockRepositoryWithMigrations_DeletedExpired_Call[T]{Call: _e.mock.On("DeletedExpired")}
}

func (_c *MockRepositoryWithMigrations_DeletedExpired_Call[T]) Run(run func()) *MockRepositoryWithMigrations_DeletedExpired_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryWithMigrations_DeletedExpired_Call[T]) Return(err error) *MockRepositoryWithMigrations_DeletedExpired_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryWithMigrations_DeletedExpired_Call[T]) RunAndReturn(run func() error) *MockRepositoryWithMigrations_DeletedExpired_Call[T] {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockRepositoryWithMigrations
func (_mock *MockRepositoryWithMigrations[T]) FindById(id uuid.UUID) (T, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (T, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) T); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepositoryWithMigrations_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockRepositoryWithMigrations_FindById_Call[T any] struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockRepositoryWithMigrations_Expecter[T]) FindById(id interface{}) *MockRepositoryWithMigrations_FindById_Call[T] {
	return &MockRepositoryWithMigrations_FindById_Call[T]{Call: _e.mock.On("FindById", id)}
}

func (_c *MockRepositoryWithMigrations_FindById_Call[T]) Run(run func(id uuid.UUID)) *MockRepositoryWithMigrations_FindById_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryWithMigrations_FindById_Call[T]) Return(v T, err error) *MockRepositoryWithMigrations_FindById_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockRepositoryWithMigrations_FindById_Call[T]) RunAndReturn(run func(id uuid.UUID) (T, error)) *MockRepositoryWithMigrations_FindById_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockRepositoryWithMigrations
func (_mock *MockRepositoryWithMigrations[T]) Insert(new T) error {
	ret := _mock.Called(new)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(T) error); ok {
		r0 = returnFunc(new)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryWithMigrations_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockRepositoryWithMigrations_Insert_Call[T any] struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - new T
func (_e *MockRepositoryWithMigrations_Expecter[T]) Insert(new interface{}) *MockRepositoryWithMigrations_Insert_Call[T] {
	return &MockRepositoryWithMigrations_Insert_Call[T]{Call: _e.mock.On("Insert", new)}
}

func (_c *MockRepositoryWithMigrations_Insert_Call[T]) Run(run func(new T)) *MockRepositoryWithMigrations_Insert_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 T
		if args[0] != nil {
			arg0 = args[0].(T)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepositoryWithMigrations_Insert_Call[T]) Return(err error) *MockRepositoryWithMigrations_Insert_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryWithMigrations_Insert_Call[T]) RunAndReturn(run func(new T) error) *MockRepositoryWithMigrations_Insert_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Migrate provides a mock function for the type MockRepositoryWithMigrations
func (_mock *MockRepositoryWithMigrations[T]) Migrate() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Migrate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepositoryWithMigrations_Migrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migrate'
type MockRepositoryWithMigrations_Migrate_Call[T any] struct {
	*mock.Call
}

// Migrate is a helper method to define mock.On call
func (_e *MockRepositoryWithMigrations_Expecter[T]) Migrate() *MockRepositoryWithMigrations_Migrate_Call[T] {
	return &MockRepositoryWithMigrations_Migrate_Call[T]{Call: _e.mock.On("Migrate")}
}

func (_c *MockRepositoryWithMigrations_Migrate_Call[T]) Run(run func()) *MockRepositoryWithMigrations_Migrate_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryWithMigrations_Migrate_Call[T]) Return(err error) *MockRepositoryWithMigrations_Migrate_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepositoryWithMigrations_Migrate_Call[T]) RunAndReturn(run func() error) *MockRepositoryWithMigrations_Migrate_Call[T] {
	_c.Call.Return(run)
	return _c
}
