// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package token

import (
	"baconi.co.uk/oauth/internal/pkg/client"
	"baconi.co.uk/oauth/internal/pkg/user"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository[T] {
	mock := &MockRepository[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository[T any] struct {
	mock.Mock
}

func (m *MockRepository[T]) Migrate() error {
	//TODO implement me
	panic("implement me")
}

type MockRepository_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockRepository[T]) EXPECT() *MockRepository_Expecter[T] {
	return &MockRepository_Expecter[T]{mock: &_m.Mock}
}

// DeleteById provides a mock function for the type MockRepository
func (_mock *MockRepository[T]) DeleteById(id uuid.UUID) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteById'
type MockRepository_DeleteById_Call[T any] struct {
	*mock.Call
}

// DeleteById is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockRepository_Expecter[T]) DeleteById(id interface{}) *MockRepository_DeleteById_Call[T] {
	return &MockRepository_DeleteById_Call[T]{Call: _e.mock.On("DeleteById", id)}
}

func (_c *MockRepository_DeleteById_Call[T]) Run(run func(id uuid.UUID)) *MockRepository_DeleteById_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteById_Call[T]) Return(err error) *MockRepository_DeleteById_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteById_Call[T]) RunAndReturn(run func(id uuid.UUID) error) *MockRepository_DeleteById_Call[T] {
	_c.Call.Return(run)
	return _c
}

// DeleteByRecord provides a mock function for the type MockRepository
func (_mock *MockRepository[T]) DeleteByRecord(record T) error {
	ret := _mock.Called(record)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByRecord")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(T) error); ok {
		r0 = returnFunc(record)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteByRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByRecord'
type MockRepository_DeleteByRecord_Call[T any] struct {
	*mock.Call
}

// DeleteByRecord is a helper method to define mock.On call
//   - record T
func (_e *MockRepository_Expecter[T]) DeleteByRecord(record interface{}) *MockRepository_DeleteByRecord_Call[T] {
	return &MockRepository_DeleteByRecord_Call[T]{Call: _e.mock.On("DeleteByRecord", record)}
}

func (_c *MockRepository_DeleteByRecord_Call[T]) Run(run func(record T)) *MockRepository_DeleteByRecord_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 T
		if args[0] != nil {
			arg0 = args[0].(T)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteByRecord_Call[T]) Return(err error) *MockRepository_DeleteByRecord_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteByRecord_Call[T]) RunAndReturn(run func(record T) error) *MockRepository_DeleteByRecord_Call[T] {
	_c.Call.Return(run)
	return _c
}

// DeletedExpired provides a mock function for the type MockRepository
func (_mock *MockRepository[T]) DeletedExpired() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeletedExpired")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeletedExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletedExpired'
type MockRepository_DeletedExpired_Call[T any] struct {
	*mock.Call
}

// DeletedExpired is a helper method to define mock.On call
func (_e *MockRepository_Expecter[T]) DeletedExpired() *MockRepository_DeletedExpired_Call[T] {
	return &MockRepository_DeletedExpired_Call[T]{Call: _e.mock.On("DeletedExpired")}
}

func (_c *MockRepository_DeletedExpired_Call[T]) Run(run func()) *MockRepository_DeletedExpired_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_DeletedExpired_Call[T]) Return(err error) *MockRepository_DeletedExpired_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeletedExpired_Call[T]) RunAndReturn(run func() error) *MockRepository_DeletedExpired_Call[T] {
	_c.Call.Return(run)
	return _c
}

// FindAllByClientId provides a mock function for the type MockRepository
func (_mock *MockRepository[T]) FindAllByClientId(clientId client.Id) ([]T, error) {
	ret := _mock.Called(clientId)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByClientId")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(client.Id) ([]T, error)); ok {
		return returnFunc(clientId)
	}
	if returnFunc, ok := ret.Get(0).(func(client.Id) []T); ok {
		r0 = returnFunc(clientId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(client.Id) error); ok {
		r1 = returnFunc(clientId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindAllByClientId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByClientId'
type MockRepository_FindAllByClientId_Call[T any] struct {
	*mock.Call
}

// FindAllByClientId is a helper method to define mock.On call
//   - clientId client.Id
func (_e *MockRepository_Expecter[T]) FindAllByClientId(clientId interface{}) *MockRepository_FindAllByClientId_Call[T] {
	return &MockRepository_FindAllByClientId_Call[T]{Call: _e.mock.On("FindAllByClientId", clientId)}
}

func (_c *MockRepository_FindAllByClientId_Call[T]) Run(run func(clientId client.Id)) *MockRepository_FindAllByClientId_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 client.Id
		if args[0] != nil {
			arg0 = args[0].(client.Id)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_FindAllByClientId_Call[T]) Return(vs []T, err error) *MockRepository_FindAllByClientId_Call[T] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockRepository_FindAllByClientId_Call[T]) RunAndReturn(run func(clientId client.Id) ([]T, error)) *MockRepository_FindAllByClientId_Call[T] {
	_c.Call.Return(run)
	return _c
}

// FindAllByUsername provides a mock function for the type MockRepository
func (_mock *MockRepository[T]) FindAllByUsername(username user.AuthenticatedUsername) ([]T, error) {
	ret := _mock.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for FindAllByUsername")
	}

	var r0 []T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(user.AuthenticatedUsername) ([]T, error)); ok {
		return returnFunc(username)
	}
	if returnFunc, ok := ret.Get(0).(func(user.AuthenticatedUsername) []T); ok {
		r0 = returnFunc(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(user.AuthenticatedUsername) error); ok {
		r1 = returnFunc(username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindAllByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllByUsername'
type MockRepository_FindAllByUsername_Call[T any] struct {
	*mock.Call
}

// FindAllByUsername is a helper method to define mock.On call
//   - username user.AuthenticatedUsername
func (_e *MockRepository_Expecter[T]) FindAllByUsername(username interface{}) *MockRepository_FindAllByUsername_Call[T] {
	return &MockRepository_FindAllByUsername_Call[T]{Call: _e.mock.On("FindAllByUsername", username)}
}

func (_c *MockRepository_FindAllByUsername_Call[T]) Run(run func(username user.AuthenticatedUsername)) *MockRepository_FindAllByUsername_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 user.AuthenticatedUsername
		if args[0] != nil {
			arg0 = args[0].(user.AuthenticatedUsername)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_FindAllByUsername_Call[T]) Return(vs []T, err error) *MockRepository_FindAllByUsername_Call[T] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockRepository_FindAllByUsername_Call[T]) RunAndReturn(run func(username user.AuthenticatedUsername) ([]T, error)) *MockRepository_FindAllByUsername_Call[T] {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockRepository
func (_mock *MockRepository[T]) FindById(id uuid.UUID) (T, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (T, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) T); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockRepository_FindById_Call[T any] struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockRepository_Expecter[T]) FindById(id interface{}) *MockRepository_FindById_Call[T] {
	return &MockRepository_FindById_Call[T]{Call: _e.mock.On("FindById", id)}
}

func (_c *MockRepository_FindById_Call[T]) Run(run func(id uuid.UUID)) *MockRepository_FindById_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_FindById_Call[T]) Return(v T, err error) *MockRepository_FindById_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockRepository_FindById_Call[T]) RunAndReturn(run func(id uuid.UUID) (T, error)) *MockRepository_FindById_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockRepository
func (_mock *MockRepository[T]) Insert(new T) error {
	ret := _mock.Called(new)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(T) error); ok {
		r0 = returnFunc(new)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockRepository_Insert_Call[T any] struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - new T
func (_e *MockRepository_Expecter[T]) Insert(new interface{}) *MockRepository_Insert_Call[T] {
	return &MockRepository_Insert_Call[T]{Call: _e.mock.On("Insert", new)}
}

func (_c *MockRepository_Insert_Call[T]) Run(run func(new T)) *MockRepository_Insert_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 T
		if args[0] != nil {
			arg0 = args[0].(T)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Insert_Call[T]) Return(err error) *MockRepository_Insert_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Insert_Call[T]) RunAndReturn(run func(new T) error) *MockRepository_Insert_Call[T] {
	_c.Call.Return(run)
	return _c
}
