// Code generated by mockery. DO NOT EDIT.

package token

import (
	client "baconi.co.uk/oauth/internal/pkg/client"
	mock "github.com/stretchr/testify/mock"

	user "baconi.co.uk/oauth/internal/pkg/user"

	uuid "github.com/google/uuid"
)

// MockToken is an autogenerated mock type for the Token type
type MockToken struct {
	mock.Mock
}

type MockToken_Expecter struct {
	mock *mock.Mock
}

func (_m *MockToken) EXPECT() *MockToken_Expecter {
	return &MockToken_Expecter{mock: &_m.Mock}
}

// GetClientId provides a mock function with no fields
func (_m *MockToken) GetClientId() client.Id {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClientId")
	}

	var r0 client.Id
	if rf, ok := ret.Get(0).(func() client.Id); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(client.Id)
	}

	return r0
}

// MockToken_GetClientId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientId'
type MockToken_GetClientId_Call struct {
	*mock.Call
}

// GetClientId is a helper method to define mock.On call
func (_e *MockToken_Expecter) GetClientId() *MockToken_GetClientId_Call {
	return &MockToken_GetClientId_Call{Call: _e.mock.On("GetClientId")}
}

func (_c *MockToken_GetClientId_Call) Run(run func()) *MockToken_GetClientId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockToken_GetClientId_Call) Return(_a0 client.Id) *MockToken_GetClientId_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockToken_GetClientId_Call) RunAndReturn(run func() client.Id) *MockToken_GetClientId_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsername provides a mock function with no fields
func (_m *MockToken) GetUsername() user.AuthenticatedUsername {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUsername")
	}

	var r0 user.AuthenticatedUsername
	if rf, ok := ret.Get(0).(func() user.AuthenticatedUsername); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(user.AuthenticatedUsername)
	}

	return r0
}

// MockToken_GetUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsername'
type MockToken_GetUsername_Call struct {
	*mock.Call
}

// GetUsername is a helper method to define mock.On call
func (_e *MockToken_Expecter) GetUsername() *MockToken_GetUsername_Call {
	return &MockToken_GetUsername_Call{Call: _e.mock.On("GetUsername")}
}

func (_c *MockToken_GetUsername_Call) Run(run func()) *MockToken_GetUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockToken_GetUsername_Call) Return(_a0 user.AuthenticatedUsername) *MockToken_GetUsername_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockToken_GetUsername_Call) RunAndReturn(run func() user.AuthenticatedUsername) *MockToken_GetUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetValue provides a mock function with no fields
func (_m *MockToken) GetValue() uuid.UUID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetValue")
	}

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	return r0
}

// MockToken_GetValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetValue'
type MockToken_GetValue_Call struct {
	*mock.Call
}

// GetValue is a helper method to define mock.On call
func (_e *MockToken_Expecter) GetValue() *MockToken_GetValue_Call {
	return &MockToken_GetValue_Call{Call: _e.mock.On("GetValue")}
}

func (_c *MockToken_GetValue_Call) Run(run func()) *MockToken_GetValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockToken_GetValue_Call) Return(_a0 uuid.UUID) *MockToken_GetValue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockToken_GetValue_Call) RunAndReturn(run func() uuid.UUID) *MockToken_GetValue_Call {
	_c.Call.Return(run)
	return _c
}

// HasExpired provides a mock function with no fields
func (_m *MockToken) HasExpired() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasExpired")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockToken_HasExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasExpired'
type MockToken_HasExpired_Call struct {
	*mock.Call
}

// HasExpired is a helper method to define mock.On call
func (_e *MockToken_Expecter) HasExpired() *MockToken_HasExpired_Call {
	return &MockToken_HasExpired_Call{Call: _e.mock.On("HasExpired")}
}

func (_c *MockToken_HasExpired_Call) Run(run func()) *MockToken_HasExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockToken_HasExpired_Call) Return(_a0 bool) *MockToken_HasExpired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockToken_HasExpired_Call) RunAndReturn(run func() bool) *MockToken_HasExpired_Call {
	_c.Call.Return(run)
	return _c
}

// IsBefore provides a mock function with no fields
func (_m *MockToken) IsBefore() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsBefore")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockToken_IsBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBefore'
type MockToken_IsBefore_Call struct {
	*mock.Call
}

// IsBefore is a helper method to define mock.On call
func (_e *MockToken_Expecter) IsBefore() *MockToken_IsBefore_Call {
	return &MockToken_IsBefore_Call{Call: _e.mock.On("IsBefore")}
}

func (_c *MockToken_IsBefore_Call) Run(run func()) *MockToken_IsBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockToken_IsBefore_Call) Return(_a0 bool) *MockToken_IsBefore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockToken_IsBefore_Call) RunAndReturn(run func() bool) *MockToken_IsBefore_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockToken creates a new instance of MockToken. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToken(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToken {
	mock := &MockToken{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
